services:
  llama-engine:
    build: ./llm
    image: my-local-rpi-llama
    container_name: llama-edge-server
    restart: unless-stopped

    volumes:
      - ./models:/models
    command: 
      - "-m"
      - "/models/model.gguf"
      - "-c"
      - "2048"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8081"
      - "-t"
      - "4"
      - "-fa"
      - "on"
    networks:
      - cv-network

  backend:
    build:
      context: ./backend
    image: cv-portfolio-backend
    container_name: cv-portfolio-backend
    restart: unless-stopped
    
    env_file:
      - ./backend/.env
    environment:
      LLAMA_HOST: llama-engine
      LLAMA_PORT: 8081
      CHROMA_PATH: /chroma_data
    volumes:
      - chroma_data:/chroma_data
    depends_on:
      - llama-engine
    networks:
      - cv-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: /api 
    image: cv-portfolio-frontend
    container_name: cv-portfolio-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - cv-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - cv-network

networks:
  cv-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  chroma_data: